### ISSUE TITLE
other language 

### ISSUE THREAD

**Issue by torisoft** [gisce/markdown-i18n#35]
Hi
I am using mkdocs for documentation. I want to use your extension but how can i configure that in mkdocs ? and how can i customize for my language (persian) ?
thanks

**Comment by ecarreras** [comment]
If you want you can look at our documentation project https://github.com/gisce/powerp-docs which uses mkdocs and two languages: Catalan (as default) and Spanish (es). We have a `mkdocs.yml` config for each language.

Hole this can be helpful for you.

**Comment by torisoft** [comment]
Thank you @ecarreras
